### ISSUE TITLE
[Request] Tales of Symphonia DoTNW

### ISSUE THREAD

**Issue by FallingSxow** [ohhsodead/ModioX#10]
This mod replaces the opening animation song for Tales of Symphonia Dawn of The New World with it's original music from the Wii
https://www.psx-place.com/threads/tales-of-symphonia-dotnw-original-op-music.29409/
Author: FallingSxow
Version: 1.0
Configuration: Singleplayer
Files: https://drive.google.com/open?id=1-T62J2SWvIo2ok4yq9a4Noijg59vNqIZ
----------------------- 
*Please include any other additional information you can find on the mods.

**Comment by FallingSxow** [comment]
I made this mod like 3 hours ago to my understanding it should work on every region of the game at least that's what i intended for it

**Comment by ohhsodead** [comment]
@FallingSxow Thanks for your contribution!

I will add this mod in the next few hours for you. Can you tell me what the install location for the file is?

**Comment by FallingSxow** [comment]
1. Download my copy of TOSR_OP_720P_OVERSEA.USM
2. Navigate to hdd0/game/GAMETITLEID/RAWDATA/MOVIE
3. Paste my file there and overwrite if it asks
4. DONE
replace GAMETITLEID with whatever the code is for the given region. the file should work for all regions to my understanding? only tested on eu copy I'll test US later as I luckily have both lol total weab. Anywho heres the ID's for the two versions I'm sure are the most compatible. (eu-NPEB01388) (us-NPUB31194)  I'll let you know for sure about the jp copy when I figure out if the file name is the same.

**Comment by ohhsodead** [comment]
Thank you! It has now been added and hopefully should work as intended. I'll also be updating this tool to allow for specific region support for mods, so expect that soon!

**Comment by FallingSxow** [comment]
Okay sounds good you'll probably hear from me again soon I'm working on a similar mod for the first symphonia game

**Comment by ohhsodead** [comment]
Great, I look forward to seeing your other mods!
