### ISSUE TITLE
Black Ops 1 Zombies for DEX

### ISSUE THREAD

**Issue by Riki-Rina** [ohhsodead/ModioX#11]
Please provide as much information you can find about the mods, also any links you can find showcasing the mods will help to find more details.
- Author: Creator / Developer
- Version: Version
- Configuration: Zombies
- Files: Download Link
----------------------- 
*Here you can include any other additional information we may need.

**Comment by ohhsodead** [comment]
@Riki-Rina

Are you requesting for some Black Ops 1 Zombies for DEX mods to be added to the tool? Please make this clear when filling out the issue details.

**Comment by ohhsodead** [comment]
> 
> 
> Please provide as much information you can find about the mods, also any links you can find showcasing the mods will help to find more details.
> 
>     * Author: Creator / Developer
> 
>     * Version: Version
> 
>     * Configuration: Zombies
> 
>     * Files: Download Link
> 
> 
> *Here you can include any other additional information we may need.

@Riki-Rina I've added a couple of mod menus for Zombies that work with DEX.
