### ISSUE TITLE
[Requencore_v8.3_ps3+Injector (1)est] 

### ISSUE THREAD

**Issue by Riki-Rina** [ohhsodead/ModioX#12]
Enter some information about the mods you'd like to be added, as well as any links you can find that showcase the mods.
Author: Creator / Developer
Version: Version
Configuration: Singleplayer / Multiplayer / Zombies
Files: Download Link
----------------------- 
*Please include any other additional information you can find on the mods.

**Comment by ohhsodead** [comment]
Zombies GSC mods are not supported by this tool. See my other tool [AtomicX](https://github.com/ohhsodead/AtomicX) which allows for injecting gsc mods to black ops 2.
