### ISSUE TITLE
Infinite Everything (EBOOT) (TLOU)

### ISSUE THREAD

**Issue by derpingel** [ohhsodead/ModioX#15]
![Vulvodynia-479b873d-4ef7-36bf-96a7-f115758849bf](https://user-images.githubusercontent.com/35424721/92638433-8cf6d380-f2da-11ea-84d4-1d152124bc54.jpg)

* Mod Name: Infinite Everything
* Mod Id: 1
* Mod Type: EBOOT
* Category: The Last of Us
* Author: RevDictator
* Version: 1.0.0
----------------------- 
*Please include additional information about the issue, details such as how to reproduce the problem, what happened before this occurred, etc...

┆Issue is synchronized with this [Bitbucket ](https://bitbucket.org/ohhsodead/modiox/issues/1/infinite-everything-eboot-tlou) by [Unito](https://www.unito.io/learn-more)

**Comment by ohhsodead** [comment]
@derpingel

What happens when you load the game? What's the exact issue you're having?

This mod maybe game region specific, so it's likely that it's supported for your region of the game. But still, I'll look into this and see what else I can find. Thanks for submitting this issue!

**Comment by ohhsodead** [comment]
@derpingel closing this due to no response from OP. Please re-open if you have any other issues with this.
