### ISSUE TITLE
[Request] Some mod menus and mod loaders

### ISSUE THREAD

**Issue by Comeb4ck** [ohhsodead/ModioX#18]
[James Reborn v40.1 Mod Loader GTA V](http://www.mediafire.com/file/hc7muteoc1a67sd/update.rpf/file) -> HEN:heavy_check_mark:  DEX:heavy_check_mark:  CFW:heavy_check_mark:
[FB14Z V2 Mod loader GTA V](http://www.mediafire.com/file/ipxmgfw1bdlmuco/update.rpf/file) -> HEN:heavy_check_mark:  DEX:heavy_check_mark:  CFW:heavy_check_mark:
[Infracted v1 MP 1080P (Bo2) SPRX](https://mega.nz/file/XiYCmbJQ#FMr2_zwqlgwj9Cl0lUo_0Os6beuUv83tVKC7gB9zZ-c)-> HEN:x:  DEX:question:  CFW:heavy_check_mark:
[Infracted v1 MP 1080P (Bo2) (HEN) SPRX](https://mega.nz/file/CixD0a7Q#RKrgxL2uJtKn-AebHINUk8Sv7MfK2-2-oehV4JsLa2U)-> HEN:heavy_check_mark:  DEX:x:  CFW:x:
[INFARCTED ZM V1 CFW 720P/1080P BO2 SPRX](https://mega.nz/file/Ku52gKiY#uVTtoi-YVL_Vg3J7DfXziD6Kc8veaokz140nf99deQo)-> HEN:x:  DEX:question:  CFW:heavy_check_mark:
[INFARCTED ZM V1 HEN 720P/1080P BO2 SPRX](https://mega.nz/file/bqI3DAJC#rE-xOZEneomjndkFdT9xI5YUD5MjC66cywrtmrfAITQ)-> HEN:heavy_check_mark:  DEX:x:  CFW:x:
[FYV7 Loader v12 Deluxe GTA V MOD LOADER](https://www.mediafire.com/file/j38fbjsjd9iyjob/FYV7_ModLoader_v12.rar/file)  -> HEN:heavy_check_mark:  DEX:heavy_check_mark:  CFW:heavy_check_mark:
[Omar Ghost Mod Loader V7.1 GTA V](http://www.mediafire.com/file/usr4cqi3yvbybg8/Omar+Ghost+Mod+Loader+V7.1.rar/file) -> HEN:heavy_check_mark:  DEX:heavy_check_mark:  CFW:heavy_check_mark:
[Black Saint v4.8 Mod Loader GTA V](http://www.mediafire.com/file/q9ckn5tujmeaa7f/Black_Saint_v4.8_Modloader.rar/file) -> HEN:heavy_check_mark:  DEX:heavy_check_mark:  CFW:heavy_check_mark:
[WE ARE GHOSTS BLES (v 1.0.1 Beta) SPRX GTA V](http://www.mediafire.com/folder/jbc5pupxh558c/WE+ARE+GHOSTS+Sprx) -> HEN:heavy_check_mark:  DEX:heavy_check_mark:  CFW:heavy_check_mark:
[WE ARE GHOSTS BLUS (v 1.0.1 Beta) SPRX GTA V](http://www.mediafire.com/folder/z3egq51yy0xr6/WE+ARE+GHOSTS+BLUS)  -> HEN:heavy_check_mark:  DEX:heavy_check_mark:  CFW:heavy_check_mark:

**Comment by ohhsodead** [comment]
@Comeb4ck 

Whoahh! Thanks for the contributions bro I appreciate it! I'll make sure they all get added when I get the time, will let you know when they're on the database.

**Comment by Comeb4ck** [comment]
@ohhsodead more mods lol
-
[One Window Challenge by NyTekCFW (BO2) (GSC) (Custom map zombies bo2 ps3)](https://www.mediafire.com/file/7mxrenkdhvbccqd/file) -> HEN:heavy_check_mark: DEX:heavy_check_mark: CFW:heavy_check_mark:
[EAG PROJECT V1.1 (Mod Loader) (GTA V) (update.rpf + eboot.bin (BLUS)](https://mega.nz/folder/r7hlSaDb#yQKhXvsvg3JZP42OraIv8g) -> HEN:heavy_check_mark: DEX:heavy_check_mark: CFW:heavy_check_mark:
[FranCangel V3.5 (Mod Loader) (GTA V)](https://www.mediafire.com/file/5t437qzmrj4zbxu/FranCangel_V3.5.rar/file) -> HEN:heavy_check_mark: DEX:heavy_check_mark: CFW:heavy_check_mark:
[The hustler 1.9 (sprx blus and bles)](https://www.mediafire.com/file/l3virligfjjqqct/The_hustler_1.9.zip/file) -> HEN:heavy_check_mark: DEX:question: CFW:question:

![rodapé-removebg](https://user-images.githubusercontent.com/66088613/100405535-8f97d800-3042-11eb-8c0c-1ea705352594.png)

**Comment by ohhsodead** [comment]
All have been added now! Thanks for requesting!
