### ISSUE TITLE
Discussion for PRs

### ISSUE THREAD

**Issue by KayGart** [ohhsodead/ModioX#19]
So I've been interested in taking a look at the project. Would it be fine with you, if I update the project to .NET 5 and start working on it? Also, I noticed DarkUI no longer has a DarkDataGridView class, so the project can't be compiled with the latest DarkUI version.

**Comment by ohhsodead** [comment]
@KayGart Hey! Thanks for your interest in my project. What kind of things are you looking to add to it? I can change framework to .NET 5 for next release, that's no problem. As for DarkUI, the fork I have hosted includes the DataGridView control and others so you should use that.

**Comment by KayGart** [comment]
Just saw the repo, nice I'll build and reference it later. As for what to add, that's a good question. I'll probably try to improve on some aspects, and see if there is any QoL things that should improve usability. I will always make PRs if I have something fleshed out and ready to merge at least.

**Comment by ohhsodead** [comment]
@KayGart Great no problem, that's fine with me! Most of the code is a mess and there some of that is stopping me from adding a couple of features I really want to add, actually.

If you have discord then we talk more about it all there if you like? Username is: ohhsodead#2519

**Comment by KayGart** [comment]
Are you in the PlayerSquared discord? I can add you from there cause I block DMs and Friends Request by default.

**Comment by ohhsodead** [comment]
@KayGart I just joined now.
