### ISSUE TITLE
[MOD REPORT] Completed Story Mode (100%) (AC3)

### ISSUE THREAD

**Issue by Flygodsa** [ohhsodead/ModioX#21]
- Mod Name: Completed Story Mode (100%) (ID#262)
- Category: Assassin's Creed III
- Mod Type: GAMESAVE
- Author: DM13
- Version: 1.0
----------------------- 
*Please include additional information about the issue, details such as how to reproduce the problem, what happened before this occurred, etc...

**Comment by ohhsodead** [comment]
@Flygodsa Hi, thanks for submitting the issue!

Can you tell me why it's not working? What happens when you the load the game?

**Comment by ohhsodead** [comment]
@Flygodsa Closing for now. Please reopen when you can provide more information to help us fix this.
