### ISSUE TITLE
[MOD REPORT] HAN Toolbox (HA)

### ISSUE THREAD

**Issue by vlad1000** [ohhsodead/ModioX#32]
- Mod Name: HAN Toolbox (ID#124)
- Category: Applications
- Mod Type: PKG
- Author: DeViL303

**Comment by ohhsodead** [comment]
@vlad1000 is this out of date? what's the problem here bro?

**Comment by ohhsodead** [comment]
> 
> 
>     * Mod Name: HAN Toolbox (ID#124)
> 
>     * Category: Applications
> 
>     * Mod Type: PKG
> 
>     * Author: DeViL303

Closing due to no reponse. Please re-open when you can provide more information (:

**Comment by vlad1000** [comment]
> > ```
> > * Mod Name: HAN Toolbox (ID#124)
> > 
> > * Category: Applications
> > 
> > * Mod Type: PKG
> > 
> > * Author: DeViL303
> > ```
> 
> Закрытие из-за отсутствия ответа. Пожалуйста,откройте снова, когда вы сможете предоставить дополнительную информацию (:

Аuto spam, meybi , automatically  send error ) .  I have a PS 3 slim ,  [CFW] 4.87.2 EVILNAT COBRA 8.20 + NoBD/NoBT , - PS 3 slim, put 500 SSD . Not enough download , speed . (game) , end soft ->  I'm tested  test  +  HEN Toolbox Mod , +  HAN Toolbox , russian language.  And then there is not enough software and tools . In Russian,-language .  .    I'm tested PS3 Tools Collection v4.8.1 (+virus)  , a lot of old, , I was looking for it , updated, DB (database) and .
I mini/hack it by 90%, Gran Turismo 6 ,  but I am no to get into (save files) , - errors . 
But I saw on the Forum 6 PT ,,, info, (Gays)  can emulate, online store,  so that, opened with online . And more cars with 4, 5 parts , were transferred to 6 GT.    Bet a From that, you can also get information about errors. But I don't send it. * *

 Translation)) sorry * Russ, Latvian , bad speak Eng
