### ISSUE TITLE
[MOD REPORT] Ultimate Toolbox (HA)

### ISSUE THREAD

**Issue by goldug** [ohhsodead/ModioX#33]
- Mod Name: Ultimate Toolbox (ID#369)
- Category: Applications
- Mod Type: PKG
- Author: DeViL303
- Version: 1.03
----------------------- 
This is IRISMAN 4.87, not Ultimate Toolbox.

**Comment by ohhsodead** [comment]
@goldug

Thanks for letting me know! I will update this.

**Comment by ohhsodead** [comment]
Fixed.
