### ISSUE TITLE
[MOD REPORT] The Outcast Menu (BF4)

### ISSUE THREAD

**Issue by Alesita66** [ohhsodead/ModioX#35]
- Mod Name: The Outcast Menu (ID#116)
- Category: Battlefield 4
- Mod Type: EBOOT/SPRX
- Author: Synful
- Version: 1.0
----------------------- 
Does not contain SPRX

**Comment by Alesita66** [comment]
Does not contain SPRX

**Comment by ohhsodead** [comment]
@Alesita66

Thanks for reporting this! I will look into it and get it updated soon as.

**Comment by ohhsodead** [comment]
Fixed.
