### ISSUE TITLE
[MOD REQUEST] xxxtentacion theme

### ISSUE THREAD

**Issue by TrxshyHub** [ohhsodead/ModioX#45]
- Name: xxxtentacion
- Category: ps3 theme
- System Type: ps3
- Author: Trxshy
- Version: ANY
- Description: PS3 THEME IIDK IF IT WORKS FOR XBOX
- Links: https://preview.redd.it/51jbr6mzdui21.jpg?width=960&crop=smart&auto=webp&s=101c04730f6036907f9429548475dabc871f3313

-----------------------

*Please include any other additional information we may need here.

**Comment by ohhsodead** [comment]
@TrxshyHub

Thanks for the request! Do you have a download link of the files?

**Comment by TrxshyHub** [comment]
[xxxtentacion theme.zip](https://github.com/ohhsodead/ModioX/files/7656530/xxxtentacion.theme.zip)
