### ISSUE TITLE
[MOD REQUEST] SKATE 3 MODS

### ISSUE THREAD

**Issue by Revan20033** [ohhsodead/ModioX#48]
- Name: SKATE 3 MODS
- Category: Skate 3 ALL DOWNLOADS RPCS
- System Type: DEX/CEX
- Author: wispp
- Version: N/A
- Description: https://drive.google.com/file/d/1EA_ExqZhXwEpp2GA_RzWpnzpCEEsStPu/view?usp=sharing
- Links: https://discord.com/channels/725753042087182406/726599125122023456/903098861772488754
------------------------
*Please include any other additional information we may need here.

**Comment by ohhsodead** [comment]
@Revan20033 I'm not sure how mods for RPC version of games work. Can you please give an example of where a file would be installed at on the console?

**Comment by Revan20033** [comment]
Open the Skate 2 and 3 Update Package Files link

Inside that link you will see 4 updates, 2 which are for skate 2, and 2 which are for skate 3.

First open up RPCS3 and check what your games serial number is, go back to the Skate 2 and 3 Update Package Files link and download the update which matches your games serial number.

After downloading the update, while the emulator is still open left click on the file and drag it into the emulator, then press yes to install.
