### ISSUE TITLE
ModioX [CRASH]

### ISSUE THREAD

**Issue by Illegal-Services** [ohhsodead/ModioX#49]
**Describe the bug**
When I launch ModioX, it crash after a few (auto-closing) windows.

**Reproduce**
1. start 'ModioX.lnk'
2. wait ~5 seconds.

**Expected Behavior**
It should normally not crash or at least let me know WHY it crashed.

**Screenshots**
https://user-images.githubusercontent.com/62464560/146623978-da145d99-1b9d-4c78-a336-a33354b42c58.mp4

**System Information (please complete the following information):**
 - OS: Windows
 - Version 10.0.19043.1415

**Comment by ohhsodead** [comment]
@Illegal-Services

Thanks for reporting! Can you please attach the log file?

**Comment by Illegal-Services** [comment]
https://github.com/ohhsodead/ModioX/files/7738515/latest.log

**Comment by ohhsodead** [comment]
> https://github.com/ohhsodead/ModioX/files/7738515/latest.log

@Illegal-Services

Thanks for the log file.

It seems there is an service issue at Dropbox and our update information file cannot be accessed at the moment. I'll let you know soon as it's been fixed. I've attached a screenshot to show the 503 error being received when trying to reach our files.

![Screenshot_20211218-014011.png](https://user-images.githubusercontent.com/17911431/146624848-4275fe67-56ff-4482-a7da-56bde7461cc1.png)

**Comment by ohhsodead** [comment]
@Illegal-Services 

It looks like it's been fixed now. Please let me know if you're still having issues or any other problems.
