### ISSUE TITLE
"Report" button not properly working?

### ISSUE THREAD

**Issue by Illegal-Services** [ohhsodead/ModioX#50]
`
%5BMOD REPORT%5D PS3™ 4K Pro (ID%23249) (PS3)&labels=mod report&assignee=ohhsodead&body=- Platform: PS3%0A- Category: Applications%0A- Name: PS3™ 4K Pro (ID%23249)%0A- System Type: CEX%2FDEX%2FHEN%0A- Mod Type: PKG%0A- Creators: Luan Teles%0A- Version: 5.1%0A- Region: n%2Fa%0A----------------------- %0A*Please include additional information about the issue, details such as how to reproduce the problem, what happened before this occurred, etc...
`
^^ Well, I think the "Report button" doesn't work, because it generate that weird title in the GitHub issue.

**Comment by ohhsodead** [comment]
@Illegal-Services

Ohh, I know the fix for this. I'll make some adjustments now to release a small update.

**Comment by ohhsodead** [comment]
Fixed in latest release (Beta v2.0.1)

**Comment by Illegal-Services** [comment]
Yeah, fixed.
