### ISSUE TITLE
HOMEBREW PS3 4K Pro "Compression not supported"

### ISSUE THREAD

**Issue by Illegal-Services** [ohhsodead/ModioX#51]
**Describe the bug**
There is an error window poping up on my screen when I try to download that HOMEBREW.
Other things I've downloaded does not had that problem.

**Reproduce**
1. Go to 'HOMEBREW'
2. Click on 'PS3 4K Pro'
3. Scroll down to 'download'

**Expected Behavior**
Download the thing correctly.

**Screenshots**
![ModioX_2021-12-20_19-17](https://user-images.githubusercontent.com/62464560/146814051-2b75e310-6142-4b3e-9759-aa7a0cec56b8.png)

**System Information (please complete the following information):**
 - OS: Windows
 - Version 10.0.19043.1415

**Comment by Illegal-Services** [comment]
[latest.log](https://github.com/ohhsodead/ModioX/files/7747255/latest.log)

**Comment by ohhsodead** [comment]
@Illegal-Services 

I made some changes and it works fine for me. Can you see if it works now for you too?

![Screenshot_1](https://user-images.githubusercontent.com/17911431/146822611-277908dc-1c8a-4cfd-a07b-2d3678271ffc.png)

**Comment by ohhsodead** [comment]
Closing because I don't have any issues. Re-open if you are still have this problem.

**Comment by Illegal-Services** [comment]
It still doesn't work for me.
Even after the new update.

**Comment by ohhsodead** [comment]
@Illegal-Services Are you still receiving an error message? For me, it just takes a while to download because it's quite a large file. It took a couple of minutes on my computer. I'll get some other people to test too.

**Comment by Illegal-Services** [comment]
yeah, let me record you the whole situation so you get more data to analyse.
I'll be back soon with the video.

**Comment by Illegal-Services** [comment]
Wait, I've just noticed that the CFW one just work fine.
But it's the HEN one that doesn't work and be an issue.
Did you tried the HEN one too?

**Comment by ohhsodead** [comment]
No I didn't check HEN, I'll look now.

**Comment by ohhsodead** [comment]
I got a "file corrupted" error so I updated the archive and now works fine. How about for you?

![Screenshot_1](https://user-images.githubusercontent.com/17911431/146836904-a3465aa3-bebd-4ce1-b49b-1f410bcfa149.png)

**Comment by Illegal-Services** [comment]
working fine now, fixed.
