### ISSUE TITLE
Exit button from "information box" disappearing (confusing).

### ISSUE THREAD

**Issue by Illegal-Services** [ohhsodead/ModioX#52]
If you compare these two screenshots, you can see that the red exit button of the second screenshot disappears when I scroll to the bottom of the page.
It confused me and I think it would be better if it would never disappear.

![ModioX_2021-12-20_22-49 (2)](https://user-images.githubusercontent.com/62464560/146837674-7be8f1cb-4e5f-4e68-906e-946ef9484b63.png)
![ModioX_2021-12-20_22-49](https://user-images.githubusercontent.com/62464560/146837677-e4c9e4df-b1fd-4235-b95b-12478911398d.png)

**Comment by ohhsodead** [comment]
Improved dialog in Beta v2.0.2
