### ISSUE TITLE
Index Startup error

### ISSUE THREAD

**Issue by Jigsaw88** [ohhsodead/ModioX#62]
**Describe the bug**
The app dont start

**Expected Behavior**
Starting 

**Screenshots**
![image](https://user-images.githubusercontent.com/71355908/162783175-860b8df1-a7e4-403a-922a-82dd884a8f47.png)

**System Information:**
 - OS: Windows
 - Version10

**Comment by ohhsodead** [comment]
Fixed in latest update (Beta v2.1.1)

**Comment by ohhsodead** [comment]
@Jigsaw88 does this fix the issue?
