### ISSUE TITLE
Tomb Raider

### ISSUE THREAD

**Issue by TATTTATTOO** [ohhsodead/ModioX#8]
Please provide as much information you can find about the mods, also any links you can find showcasing the mods will help to find more details.
- Game: Tomb Raider
- Author: Core / Aspyr
- Version: 1.0
----------------------- 
*Here you can include any other additional information we may need.

**Comment by ohhsodead** [comment]
Hello @TATTTATTOO, thanks for the suggestion.

But do you have any mods for this game you can provide? Any links or downloads will be great help, it will make it easier for me find and contribute them for you.

**Comment by ohhsodead** [comment]
> 
> 
> Please provide as much information you can find about the mods, also any links you can find showcasing the mods will help to find more details.
> 
>     * Game: Tomb Raider
> 
>     * Author: Core / Aspyr
> 
>     * Version: 1.0
> 
> 
> *Here you can include any other additional information we may need.

@TATTTATTOO I've now added some mods for this game title.
